insert into Products (Name, Price) values ('Wiberg Cure', 12758.64);
insert into Products (Name, Price) values ('Eggplant Italian', 5402.37);
insert into Products (Name, Price) values ('Oven Mitts - 15 Inch', 14122.92);
insert into Products (Name, Price) values ('Wine - Fino Tio Pepe Gonzalez', 7288.45);
insert into Products (Name, Price) values ('Beer - True North Strong Ale', 11256.7);
insert into Products (Name, Price) values ('Island Oasis - Magarita Mix', 13111.69);
insert into Products (Name, Price) values ('Ecolab - Medallion', 2037.78);
insert into Products (Name, Price) values ('Lettuce - Boston Bib', 1002.53);
insert into Products (Name, Price) values ('Olives - Stuffed', 5906.8);
insert into Products (Name, Price) values ('Carbonated Water - Wildberry', 4617.65);
insert into Products (Name, Price) values ('Bread - Crumbs, Bulk', 4850.61);
insert into Products (Name, Price) values ('Containter - 3oz Microwave Rect.', 3078.83);
insert into Products (Name, Price) values ('Pumpkin - Seed', 2528.8);
insert into Products (Name, Price) values ('Olives - Black, Pitted', 14933.2);
insert into Products (Name, Price) values ('Tart Shells - Savory, 3', 1417.76);
insert into Products (Name, Price) values ('Juice - Orange, Concentrate', 5706.31);
insert into Products (Name, Price) values ('Clementine', 7332.39);
insert into Products (Name, Price) values ('Yeast Dry - Fleischman', 13996.84);
insert into Products (Name, Price) values ('Bread - Granary Small Pull', 11148.56);
insert into Products (Name, Price) values ('Tequila - Sauza Silver', 1700.29);